apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 80          # Cluster-internal port
      targetPort: 80     # Container port
      nodePort: 31000    # Externally accessible Node port (range: 30000-32767)

